---
apiVersion: v1
kind: Namespace
metadata:
  name: web-app

---
apiVersion: v1
kind: Pod
metadata:
  name: web-fastapi-app
  namespace: web-app
  labels:
    name: web-fastapi-app
spec:
  containers:
  - name: web-fastapi-app-container
    image: docker.io/gmtdocker/my-fast-api
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    imagePullPolicy: IfNotPresent
